from sys import argv

scriptName, fileName = argv
text = open(fileName)
print()
print("Here is your file: %r" % fileName)
print(text.read())
text.close()
print('We are going to erase %r.' % fileName)
print('If you don\'t want to erase, hit CTRL - C (^C).')
print('If you want to continue, hit RETURN.')
print()
prompt = input('? ')
target = open(fileName, 'w')
print()
print('Opening {} and truncating its contents.\nWait! Wait!! Wait!!!'.format(fileName))
target.truncate()
print()
print('Now I am going to ask you for three (3) lines.')
print()
line1 = input('Line One: ')
line2 = input('Line Two: ')
line3 = input('Line Three: ')
print()
print('I am going to write these lines to the file now.')
target.write(line1)
target.write('\n')
target.write(line2)
target.write('\n')
target.write(line3)
target.write('\n')
print('The file {} has been overwritten.'.format(fileName))
target.close()
print()
newText = open(fileName)
print("Here is the new content of your file: %r" % fileName)
print(newText.read())
newText.close()
